server:
  port: 8080

spring:
  application:
    name: demo-provider
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true



